// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShelter.Data;

#nullable disable

namespace PetShelter.Migrations
{
    [DbContext(typeof(Db_Context))]
    [Migration("20250426125238_V2")]
    partial class V2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetShelter.Models.AdoptionRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdopterId_FK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Approved_At")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId_FK")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shelter_FK")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdopterId_FK");

                    b.HasIndex("PetId_FK");

                    b.HasIndex("Shelter_FK");

                    b.ToTable("AdoptionRequest");
                });

            modelBuilder.Entity("PetShelter.Models.Animal", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Adoption_State")
                        .HasColumnType("int");

                    b.Property<int>("Category_FK")
                        .HasColumnType("int");

                    b.Property<int?>("Shelter_FK")
                        .HasColumnType("int");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("medication_history")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("Category_FK");

                    b.HasIndex("Shelter_FK");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("PetShelter.Models.Interview", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("AdoptionRequest_fk")
                        .HasColumnType("int");

                    b.Property<DateTime?>("InterviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("AdoptionRequest_fk")
                        .IsUnique();

                    b.ToTable("Interviews");
                });

            modelBuilder.Entity("PetShelter.Models.Shelter", b =>
                {
                    b.Property<int>("ShelterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShelterID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShelterName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ShelterID");

                    b.ToTable("Shelters");
                });

            modelBuilder.Entity("PetShelter.Models.ShelterCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Shelter_FK")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("Shelter_FK");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PetShelter.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Activated")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("Banned_At")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PetShelter.Models.Admin", b =>
                {
                    b.HasBaseType("PetShelter.Models.User");

                    b.Property<int>("AdminType")
                        .HasColumnType("int");

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("PetShelter.Models.Adopter", b =>
                {
                    b.HasBaseType("PetShelter.Models.User");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Adopters", (string)null);
                });

            modelBuilder.Entity("PetShelter.Models.ShelterStaff", b =>
                {
                    b.HasBaseType("PetShelter.Models.User");

                    b.Property<DateOnly?>("HiredDate")
                        .HasColumnType("date");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shelter_FK")
                        .HasColumnType("int");

                    b.Property<int>("StaffType")
                        .HasColumnType("int");

                    b.HasIndex("Shelter_FK");

                    b.ToTable("ShelterStaff", (string)null);
                });

            modelBuilder.Entity("PetShelter.Models.AdoptionRequest", b =>
                {
                    b.HasOne("PetShelter.Models.Adopter", "Adopter")
                        .WithMany()
                        .HasForeignKey("AdopterId_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShelter.Models.Animal", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetShelter.Models.Shelter", "Shelter")
                        .WithMany()
                        .HasForeignKey("Shelter_FK")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adopter");

                    b.Navigation("Pet");

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("PetShelter.Models.Animal", b =>
                {
                    b.HasOne("PetShelter.Models.ShelterCategory", "ShelterCategory")
                        .WithMany("Animal")
                        .HasForeignKey("Category_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShelter.Models.Shelter", "Shelter")
                        .WithMany("Animals")
                        .HasForeignKey("Shelter_FK")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Shelter");

                    b.Navigation("ShelterCategory");
                });

            modelBuilder.Entity("PetShelter.Models.Interview", b =>
                {
                    b.HasOne("PetShelter.Models.AdoptionRequest", "AdoptionRequest")
                        .WithOne()
                        .HasForeignKey("PetShelter.Models.Interview", "AdoptionRequest_fk")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdoptionRequest");
                });

            modelBuilder.Entity("PetShelter.Models.ShelterCategory", b =>
                {
                    b.HasOne("PetShelter.Models.Shelter", "Shelter")
                        .WithMany("Category")
                        .HasForeignKey("Shelter_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("PetShelter.Models.Admin", b =>
                {
                    b.HasOne("PetShelter.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PetShelter.Models.Admin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetShelter.Models.Adopter", b =>
                {
                    b.HasOne("PetShelter.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PetShelter.Models.Adopter", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PetShelter.Models.ShelterStaff", b =>
                {
                    b.HasOne("PetShelter.Models.User", null)
                        .WithOne()
                        .HasForeignKey("PetShelter.Models.ShelterStaff", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShelter.Models.Shelter", "Shelter")
                        .WithMany("Staff")
                        .HasForeignKey("Shelter_FK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelter");
                });

            modelBuilder.Entity("PetShelter.Models.Shelter", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Category");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("PetShelter.Models.ShelterCategory", b =>
                {
                    b.Navigation("Animal");
                });
#pragma warning restore 612, 618
        }
    }
}
